### ISSUE TITLE
[FEATURE] Add support for Three Winding Transformers

### ISSUE THREAD

**Issue by Thijss** [alliander-opensource/power-grid-model#12]
**Describe the feature request**

It would be nice to include support network configurations with so-called three winding transformers.

In my understanding these transformers can connect three nodes with different voltage levels.

In the current data model, a Transformer can only connect two nodes: (`from_node`) and (`to_node`)

current:
```
[from_node]--[transformer]--[to_node]
```

requested support for:
```
[node_1]--[transformer]--[node_2]
                     |
                     |--[node_3]
```

**Acceptance criteria**
- [ ] Implemented ThreeWindingTransformer 
- [ ] Unit tests for ThreeWindingTransformer
- [ ] Validated with pandapower for symmetric calculations
- [ ] Added validation of values to `validate_input_data` and `validate_batch_data`
- [ ] Documentation updated

**Comment by aditya-hekker** [comment]
@Thijss , @TonyXiang8787  we will pick this up in the first following sprint. Which runs from 9-23 feb.
