### ISSUE TITLE
Create node injection as a measured terminal type for power sensor

### ISSUE THREAD

**Issue by TonyXiang8787** [alliander-opensource/power-grid-model#166]
Sometimes you want to assign the total injection power measurement into a node. Currently it is not possible. We need to create a new `MeasuredTerminalType` as `node_injection`. When this is given, it will be used directly as the injection measurement in the state estimation core.

**Comment by bramstoeller** [comment]
To calculate the residuals, we need the calculated node injection, right? Should we add that to the node output data?

**Comment by TonyXiang8787** [comment]
@bramstoeller you are correct. You need to add mode injection in the math output. Probably you can also choose to add it to the component output.
