### ISSUE TITLE
[BUG] Segmentation Fault when running calculate_power_flow() for >=1.3.250

### ISSUE THREAD

**Issue by Thijss** [alliander-opensource/power-grid-model#69]
**Describe the bug**

Starting from 1.3.250 I am getting segmentation faults when running `.calculate_power_flow()`

**Input Data Validity**

Did you check the validity of input data using the helper function, see examples
[here](../blob/main/examples/Validation Examples.ipynb)?

**Data Dump**

no datadump for now since I am not sure whether I can share the data outside alliander. Shared internally with @TonyXiang8787 

**To Reproduce**

```python
input_data = load_json()
model = PowerGridModel(input_data, system_frequency=50.0)
model.calculate_power_flow(calculation_method=CalculationMethod.linear)
```

**Expected behavior**

A traceback instead of a segmentation fault would be helpful.

**Comment by Thijss** [comment]
1.3.248 also still works

**Comment by TonyXiang8787** [comment]
Last working version `1.3.249`
With commit hash `f30a6ca8225161478029a3479bd2f50bbe40d4ed`
